### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rcxdude** [IvanZuy/freertos_c28x#6]
Your README states that the repo is licensed under the "FreeRTOS Open Source License", but the link provided now points to the updated license for FreeRTOS, which is MIT, while the license header in the source code still refers to the old license, which is GPL with a static linking exception. At the moment it would still seem this is the license the project uses, but it would be good to either update the license to reflect the FreeRTOS MIT license (if you're willing to do so), or include the full text of the old FreeRTOS in the repo, to make the licensing situation clearer.

**Comment by IvanZuy** [comment]
Thank you for bringing my attention to this issue. License is changed to MIT.
